Set-WindowsExplorerOptions -EnableShowFileExtension -EnableShowFullPathInTitleBar
Enable-MicrosoftUpdate
Update-ExecutionPolicy RemoteSigned
Set-StartScreenOptions -EnableDesktopBackgroundOnStart -EnableShowAppsViewOnStartScreen -EnableSearchEverywhereInAppsView